name: rollcrits

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  angular:
  angular_components:
  angular_modern_charts:
  swlegion:
  swlegion_simulator:
    path:
      ../swlegion_simulator

dev_dependencies:
  angular_test:
  build_runner:
  build_test:
  build_web_compilers:
  pedantic:
  sass_builder:
  test:
  webdev:

dependency_overrides:
  swlegion:
    path: ../swlegion
