name: rollcrits

dependencies:
  angular:
  angular_components:
  angular_modern_charts:
  swlegion:

dev_dependencies:
  angular_test:
  build_runner:
  build_test:
  build_web_compilers:
  pedantic:
  sass_builder:
  test:
  webdev:

dependency_overrides:
  swlegion:
    path: ../../hquplink/swlegion
