name: rollcrits

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  angular: ^6.0.0-alpha
  angular_components: ^0.14.0-alpha 
  angular_modern_charts: ^0.2.0

  # TODO: Remove from dependency_overrides and version.
  swlegion:
  swlegion_simulator:

dev_dependencies: 
  build_runner: ^1.6.1
  build_web_compilers: ^2.1.4
  peanut: ^3.2.1
  pedantic: ^1.8.0+1
  sass_builder: ^2.1.3
  webdev: ^2.2.0

dependency_overrides:
  swlegion:
    path: ../swlegion
  swlegion_simulator:
    path: ../swlegion_simulator
